In [1]:
import folium
import pandas as pd

from folium.plugins import MarkerCluster
from folium.plugins import MousePosition
from folium.features import DivIcon

In [2]:
import requests
import io


URL = 'https://cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud/IBM-DS0321EN-SkillsNetwork/datasets/spacex_launch_geo.csv'
resp = requests.get(URL)
spacex_csv_file = io.BytesIO(resp.content)
spacex_df=pd.read_csv(spacex_csv_file)

In [3]:
# Select relevant sub-columns: `Launch Site`, `Lat(Latitude)`, `Long(Longitude)`, `class`
spacex_df = spacex_df[['Launch Site', 'Lat', 'Long', 'class']]
launch_sites_df = spacex_df.groupby(['Launch Site'], as_index=False).first()
launch_sites_df = launch_sites_df[['Launch Site', 'Lat', 'Long']]
launch_sites_df

    Launch Site        Lat        Long
0   CCAFS LC-40  28.562302  -80.577356
1  CCAFS SLC-40  28.563197  -80.576820
2    KSC LC-39A  28.573255  -80.646895
3   VAFB SLC-4E  34.632834 -120.610745

In [4]:
# Start location is NASA Johnson Space Center
nasa_coordinate = [29.559684888503615, -95.0830971930759]
site_map = folium.Map(location=nasa_coordinate, zoom_start=10)

In [5]:
# Create a blue circle at NASA Johnson Space Center's coordinate with a popup label showing its name
circle = folium.Circle(nasa_coordinate, radius=1000, color='#d35400', fill=True).add_child(folium.Popup('NASA Johnson Space Center'))
# Create a blue circle at NASA Johnson Space Center's coordinate with a icon showing its name
marker = folium.map.Marker(
    nasa_coordinate,
    # Create an icon as a text label
    icon=DivIcon(
        icon_size=(20,20),
        icon_anchor=(0,0),
        html='<div style="font-size: 12; color:#d35400;"><b>%s</b></div>' % 'NASA JSC',
        )
    )
site_map.add_child(circle)
site_map.add_child(marker)

In [6]:
LC_40_coordinate = [28.562302, -80.577356]
site_map_1 = folium.Map(location=LC_40_coordinate, zoom_start=10)
SLC_40_coordinate = [28.563197, -80.576820]
site_map_2 = folium.Map(location=SLC_40_coordinate, zoom_start=10)
LC_39A_coordinate = [28.573255,-80.646895]
site_map_3 = folium.Map(location=LC_39A_coordinate, zoom_start=10)
SLC_4E_coordinate = [34.632834,-120.610745]
site_map_4 = folium.Map(location=SLC_4E_coordinate, zoom_start=10)

In [7]:
circle = folium.Circle(nasa_coordinate, radius=1000, color='#d35400', fill=True).add_child(folium.Popup('NASA Johnson Space Center'))
# Create a blue circle at NASA Johnson Space Center's coordinate with a icon showing its name
marker = folium.map.Marker(
    nasa_coordinate,
    # Create an icon as a text label
    icon=DivIcon(
        icon_size=(20,20),
        icon_anchor=(0,0),
        html='<div style="font-size: 12; color:#d35400;"><b>%s</b></div>' % 'NASA JSC',
        )
    )
site_map.add_child(circle)
site_map.add_child(marker)


# Create circle and marker for CCAFS LC 40
circle_LC_40 = folium.Circle(LC_40_coordinate, radius=1000, color='#d35400', fill=True).add_child(folium.Popup('LC 40'))
marker_LC_40 = folium.map.Marker(
    LC_40_coordinate,
    icon=DivIcon(
        icon_size=(20,20),
        icon_anchor=(0,0),
        html='<div style="font-size: 12; color:#d35400;"><b>%s</b></div>' % 'LC 40',
        )
    )
# Add the circle and marker to the map, not the coordinates
site_map.add_child(circle_LC_40)  # Changed from CCAFS_LC_40_Coordinates to circle_LC_40
site_map.add_child(marker_LC_40)  # Changed from CCAFS_LC_40_Coordinates to marker_LC_40


# Create circle and marker for CCAFS SLC 40
circle_SLC_40 = folium.Circle(SLC_40_coordinate, radius=1000, color='#d35400', fill=True).add_child(folium.Popup('SLC 40'))
marker_SLC_40 = folium.map.Marker(
    SLC_40_coordinate,
    icon=DivIcon(
        icon_size=(20,20),
        icon_anchor=(0,0),
        html='<div style="font-size: 12; color:#d35400;"><b>%s</b></div>' % 'SLC 40',
        )
    )
# Add the circle and marker to the map, not the coordinates
site_map.add_child(circle_SLC_40)  # Changed from CCAFS_SLC_40_Coordinates to circle_SLC_40
site_map.add_child(marker_SLC_40)  # Changed from CCAFS_SLC_40_Coordinates to marker_SLC_40



# Create circle and marker for KSC LC 39A
circle_LC_39A = folium.Circle(LC_39A_coordinate, radius=1000, color='#d35400', fill=True).add_child(folium.Popup('LC 39 A'))
marker_LC_39A = folium.map.Marker(
    LC_39A_coordinate,
    icon=DivIcon(
        icon_size=(20,20),
        icon_anchor=(0,0),
        html='<div style="font-size: 12; color:#d35400;"><b>%s</b></div>' % 'LC 39 A',
        )
    )
# Add the circle and marker to the map, not the coordinates
site_map.add_child(circle_LC_39A)  # Changed from KSC_LC_39A_Coordinates to circle_LC_39A
site_map.add_child(marker_LC_39A)  # Changed from KSC_LC_39A_Coordinates to marker_LC_39A


# Create circle and marker for VAFB SLC 4E
circle_SLC_4E = folium.Circle(SLC_4E_coordinate, radius=1000, color='#d35400', fill=True).add_child(folium.Popup('SLC 4E'))
marker_SLC_4E = folium.map.Marker(
    SLC_4E_coordinate,
    icon=DivIcon(
        icon_size=(20,20),
        icon_anchor=(0,0),
        html='<div style="font-size: 12; color:#d35400;"><b>%s</b></div>' % 'VAFB_SLC_4E',
        )
    )
# Add the circle and marker to the map, not the coordinates
site_map.add_child(circle_SLC_4E)  # Changed from VAFB_SLC_4E_Coordinates to circle__SLC_4E
site_map.add_child(marker_SLC_4E)  # Changed from VAFB_SLC_4E_Coordinates to marker_SLC_4E

In [8]:
spacex_df.tail(10)

     Launch Site        Lat       Long  class
46    KSC LC-39A  28.573255 -80.646895      1
47    KSC LC-39A  28.573255 -80.646895      1
48    KSC LC-39A  28.573255 -80.646895      1
49  CCAFS SLC-40  28.563197 -80.576820      1
50  CCAFS SLC-40  28.563197 -80.576820      1
51  CCAFS SLC-40  28.563197 -80.576820      0
52  CCAFS SLC-40  28.563197 -80.576820      0
53  CCAFS SLC-40  28.563197 -80.576820      0
54  CCAFS SLC-40  28.563197 -80.576820      1
55  CCAFS SLC-40  28.563197 -80.576820      0

In [9]:
marker_cluster = MarkerCluster()

In [10]:
def assign_marker_color(launch_outcome):
    if launch_outcome == 1:
        return 'green'
    else:
        return 'red'
    
spacex_df['marker_color'] = spacex_df['class'].apply(assign_marker_color)
spacex_df.tail(10)

     Launch Site        Lat       Long  class marker_color
46    KSC LC-39A  28.573255 -80.646895      1        green
47    KSC LC-39A  28.573255 -80.646895      1        green
48    KSC LC-39A  28.573255 -80.646895      1        green
49  CCAFS SLC-40  28.563197 -80.576820      1        green
50  CCAFS SLC-40  28.563197 -80.576820      1        green
51  CCAFS SLC-40  28.563197 -80.576820      0          red
52  CCAFS SLC-40  28.563197 -80.576820      0          red
53  CCAFS SLC-40  28.563197 -80.576820      0          red
54  CCAFS SLC-40  28.563197 -80.576820      1        green
55  CCAFS SLC-40  28.563197 -80.576820      0          red

In [11]:
site_map.add_child(marker_cluster)

# for each row in spacex_df data frame
# create a Marker object with its coordinate
# and customize the Marker's icon property to indicate if this launch was successed or failed, 
# e.g., icon=folium.Icon(color='white', icon_color=row['marker_color']
for index, record in spacex_df.iterrows():
    marker = folium.Marker([record['Lat'], record['Long']], 
                  icon=folium.Icon(color='white', icon_color=record['marker_color']))
    marker_cluster.add_child(marker)

site_map

In [12]:
# Add Mouse Position to get the coordinate (Lat, Long) for a mouse over on the map
formatter = "function(num) {return L.Util.formatNum(num, 5);};"
mouse_position = MousePosition(
    position='topright',
    separator=' Long: ',
    empty_string='NaN',
    lng_first=False,
    num_digits=20,
    prefix='Lat:',
    lat_formatter=formatter,
    lng_formatter=formatter,
)

site_map.add_child(mouse_position)
site_map

In [13]:
from math import sin, cos, sqrt, atan2, radians
import numpy as np

def calculate_distance(lat1, lon1, lat2, lon2):
    # approximate radius of earth in km
    R = 6373.0

    lat1 = radians(lat1)
    lon1 = radians(lon1)
    lat2 = radians(lat2)
    lon2 = radians(lon2)

    dlon = lon2 - lon1
    dlat = lat2 - lat1

    a = sin(dlat / 2)**2 + cos(lat1) * cos(lat2) * sin(dlon / 2)**2
    c = 2 * atan2(sqrt(a), sqrt(1 - a))

    distance = R * c
    return distance

In [14]:
#### Distance near NASA JSC

point_a = [(29.559684888503615, -95.0830971930759), ]
point_b = [(29.29838, -94.72896), ]
matrix1 = np.array([[calculate_distance(lat1, lon1, lat2, lon2)
                    for lat2, lon2 in point_a]
                   for lat1, lon1 in point_b])

##### Distance near SLC,LC 
point_c = [(28.563197, -80.576820),
          (28.562302, -80.577356),]
point_d = [(28.57352, -80.57031), 
          (28.56296, -80.56772),]
matrix2 = np.array([[calculate_distance(lat1, lon1, lat2, lon2)
                    for lat2, lon2 in point_c]
                   for lat1, lon1 in point_d])
#### Distance near SLC_4E
point_e = [(34.632834,-120.610745), ]
point_f = [(34.63293, -120.62601), ]
matrix3 = np.array([[calculate_distance(lat1, lon1, lat2, lon2)
                    for lat2, lon2 in point_e]
                   for lat1, lon1 in point_f])


print(matrix1, matrix2, matrix3)

[[44.96434212]] [[1.31257268 1.42503085]
 [0.8893897  0.94420682]] [[1.39710975]]

In [15]:
lat2 = 28.56296
lon2 = -80.56772
distance = 0.94420682  # Changed variable name from distance_marker to distance

distance_marker = folium.Marker(
    [lat2, lon2],  # Using variables directly
    icon=DivIcon(
        icon_size=(20,20),
        icon_anchor=(0,0),
        html='<div style="font-size: 12; color:#d35400;"><b>%s</b></div>' % "{:10.2f} KM".format(distance),
        )
    )
lat3 = 28.57352
lon3 = -80.57031
distance1 = 0.88933897  # Changed variable name from distance_marker to distance

distance_marker = folium.Marker(
    [lat3, lon3],  # Using variables directly
    icon=DivIcon(
        icon_size=(20,20),
        icon_anchor=(0,0),
        html='<div style="font-size: 12; color:#d35400;"><b>%s</b></div>' % "{:10.2f} KM".format(distance1),
        )
    )
lat4 = 34.63293
lon4 = -120.62601
distance2 = 1.39710975  # Changed variable name from distance_marker to distance

distance_marker = folium.Marker(
    [lat4, lon4],  # Using variables directly
    icon=DivIcon(
        icon_size=(20,20),
        icon_anchor=(0,0),
        html='<div style="font-size: 12; color:#d35400;"><b>%s</b></div>' % "{:10.2f} KM".format(distance2),
        )
    )

In [16]:
# Create a list of coordinate pairs
coordinates = [[29.559684888503615, -95.0830971930759], [29.29838, -94.72896]] 
coordinates1 = [[28.57471, -80.64772], [28.57532, -80.57096]] 
coordinates2 = [[28.562302, -80.577356], [28.56236, -80.56542]] 
coordinates3 = [[34.632834,-120.610745], [34.63293, -120.6260]] 

# Create the PolyLine with the list of coordinates
lines = folium.PolyLine(locations=coordinates, weight=5)
lines1 = folium.PolyLine(locations=coordinates1, weight=5)
lines2 = folium.PolyLine(locations=coordinates2, weight=5)
lines3 = folium.PolyLine(locations=coordinates3, weight=5)

# Add each line to the map separately - add_child() only accepts one child at a time
site_map.add_child(lines)
site_map.add_child(lines1)
site_map.add_child(lines2)
site_map.add_child(lines3)